name: "DEV Test and Publish"

on:
  push:
    branches:
      - dev

env:
  FACTIVA_USERKEY: ${{secrets.FACTIVA_USERKEY}}
  FACTIVA_CLIENTID: ${{secrets.FACTIVA_CLIENTID}}
  FACTIVA_USERNAME: ${{secrets.FACTIVA_USERNAME}}
  FACTIVA_PASSWORD: ${{secrets.FACTIVA_PASSWORD}}
  FACTIVA_CLIENT_EMAIL: ${{vars.FACTIVA_CLIENT_EMAIL}}
  FACTIVA_SNAPSHOTID: ${{vars.FACTIVA_SNAPSHOTID}}
  FACTIVA_SNAPSHOT_UPDATEID: ${{vars.FACTIVA_SNAPSHOT_UPDATEID}}
  FACTIVA_STREAMID: ${{secrets.FACTIVA_STREAMID}}
  FACTIVA_WHERE: ${{vars.FACTIVA_WHERE}}
  FACTIVA_SUBSCRIPTIONID: ${{secrets.FACTIVA_SUBSCRIPTIONID}}
  FACTIVA_LOGLEVEL: ${{vars.FACTIVA_LOGLEVEL}}

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: 'dev'

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install latest PIP
        run: |
          python -m pip install --upgrade pip >> $GITHUB_OUTPUT

      - name: Install Dependencies
        run: |
          python -m pip install pytest pytest-cov >> $GITHUB_OUTPUT

      - name: Setup factiva-analytics <DEV> (this repo)
        run: |
          python -m pip install -e . >> $GITHUB_OUTPUT

      - name: pytest
        run: pytest test/ >> $GITHUB_OUTPUT

  build:
      name: Build and Publish
      runs-on: ubuntu-latest
      needs: [test]
      steps:
        - name : Checkout code
          uses : actions/checkout@v3
          with:
            ref: 'dev'

        - name: Set up Python
          uses: actions/setup-python@v3
          with:
            python-version: '3.9'

        - name: Install latest pip, setuptools, twine + wheel
          run: |
            python -m pip install --upgrade pip setuptools wheel >> $GITHUB_OUTPUT
            
        - name: Build wheels
          run: |
            python setup.py bdist_wheel >> $GITHUB_OUTPUT
            python setup.py sdist >> $GITHUB_OUTPUT

        - name: Upload Artifact
          uses: actions/upload-artifact@v3
          with:
            name: Wheel_library
            path: dist/
            
        - name: Publish package to TestPyPI
          uses: pypa/gh-action-pypi-publish@release/v1
          with:
            user: __token__
            password: ${{ secrets.TEST_PYPI_API_TOKEN }}
            repository_url: https://test.pypi.org/legacy/
            skip_existing: true
